Reviewers
DaniilRuchkin/FileSharingService pull request #1
Opened 2024-07-02 10:08 UTC by DaniilRuchkin

2024-07-08 10:45 UTC, a-kalashnikov requested changes

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +        var filePath = await services.FileSaveAsync(createFileDto);
1) SaveFileAsync*
2) нужно пробрасывать CancellationToken в асинхронные методы

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +[TypeFilter(typeof(NullCheckExceptionFilter))]
зачем?

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +[Route("api/files")]
нет версии апи

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +        return Ok(filePath);
не нужно из апи возвращать примитивы. Создай модель ответа унифицированную и используй ее

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +    public async Task<IActionResult> GetFileAsync([Required] string uniqueFileName)
нужно явно указывать, откуда берется параметр. Предполагаю, что uniqueFileName берется из route-параметра api/v1/file/{fileName}

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +        var filePath = Path.Combine(webRoot, dowloadedFile.UniqueName);
это бизнес логика, она не должна быть в контроллере

2024-07-08 10:45 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +        return Ok(fileToDelete);
та же ошибка

2024-07-08 10:45 UTC, a-kalashnikov commented on DTO/CreateFileDto.cs
> +    [Required, MinLength(3), MaxLength(64)]
в целом валидационные атрибуты ок, но в следующей задаче (как и в будущих проектах) лучше использовать свои валидаторы

2024-07-08 10:45 UTC, a-kalashnikov commented on DTO/CreateFileDto.cs
> +    public string Password { get; set; } = string.Empty;
зачем пустая строка по умолчанию?

2024-07-08 10:45 UTC, a-kalashnikov commented on DTO/FileDeleteDto.cs
> +    public string Password {  get; set; } = string.Empty;
лишний пробел + зачем тут тоже по умолчанию пустая строка?

2024-07-08 10:45 UTC, a-kalashnikov commented on DbContextFile/ManagementDbContext.cs
> +public class ManagementDbContext(DbContextOptions<ManagementDbContext> options) : DbContext(options)
Что значит Management в контексте этой задачи? Обычно контекст называют так же, как и базу данных, т.к это DB контекст

2024-07-08 10:45 UTC, a-kalashnikov commented on Filters/NullCheckExceptionFilter.cs
> +        {
бесполезный фильтр

2024-07-08 10:45 UTC, a-kalashnikov commented on Models/EntityFile.cs
> +    public string UniqueName { get; set; } = string.Empty;
зачем пустые строки по умолчанию?

2024-07-08 10:45 UTC, a-kalashnikov commented on Models/EntityFile.cs
> +public class EntityFile
не нужно использовать префикс Entity для доменных моделей, нужно сделать так, чтобы они лежали в отдельном неймспейсе

2024-07-08 10:45 UTC, a-kalashnikov commented on .env
> +DATABASE_USER=postgres
нельзя в репозиторий выкладывать креды для подключения, нужно создавать example.env и там описывать требуемые параметры

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/IRepository.cs
> +        public Task SaveFileAsync(EntityFile entity);
поправь форматирование

2024-07-08 10:45 UTC, a-kalashnikov commented on Models/EntityFile.cs
> +    public DateTime Time { get; set; }
Нужно называть поля так, чтобы было понятно, что они в себе хранят. В данном случае не понятно, что это за время - создания, обновления и тд. Почитай как такие поля обычно называют

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/IRepository.cs
> +        public Task DeleteFileAsync(EntityFile entityFile);
пробелы между методами должны быть

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/IRepository.cs
> +        public Task DeleteFileTimeAsync(DateTime deleteTime);
из названия не понятно, что делает метод

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/IRepository.cs
> +public interface IRepository
если репозиторий для всех сущностей, то непонятно, почему в названии методов File. Если конкретно для файлов, это нужно отражать в названии

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/Repository.cs
> +public class Repository(ManagementDbContext appDbContext) : IRepository
То же самое, если это репозиторий для файлов, нужно это указывать

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/Repository.cs
> +        await appDbContext.SaveChangesAsync();
1) нужно пробрасывать CancellationToken
2) файлов по такому условию может быть много, выгружать их все в память нерационально, подумай, как можно это исправить
3) этот метод, кажется, не работает как нужно. а точнее, он не удаляет из бд записи, проверь, так ли это

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesCleanServices.cs
> +        int cleanIntervalDays = configuration.GetValue<int>("CleanupSettings:CleanupIntervalDays");
используй IOptions и иньекти его сразу в сервис, а не всю конфигурацию

2024-07-08 10:45 UTC, a-kalashnikov commented on Repositories/Repository.cs
> +            File.Delete(file.FilePath);
это бизнес логика, репозиторий - data access, перенеси все

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesServices.cs
> +public class FilesServices(IWebHostEnvironment webHostEnvironment, IRepository repository) : IFilesServices
FileService

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesServices.cs
> +        var passwordHasher = new PasswordHasher<string>();
используй DI

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesServices.cs
> +
в if нужно проверять крайние случаи, а не общий

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesServices.cs
> +            File.Delete(fileToDelete.FilePath);
лучше сначала удалять из фс, а потом из бд

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/FilesServices.cs
> +        await using (var stream = new FileStream(filePath, FileMode.Create))
в FileStream есть флаг, который указывает, что он асинхронный

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/IFilesServices.cs
> +    public Task<bool> DeleteFileAsync(FileDeleteDto fileDeleteDto);
новые строки между методами + в разных слоях приложения должны быть свои модели

2024-07-08 10:45 UTC, a-kalashnikov commented on Services/IFilesServices.cs
> +public interface IFilesServices
IFileService

2024-07-08 11:41 UTC, DaniilRuchkin commented on Controllers/FileContoller.cs
> +    public async Task<IActionResult> GetFileAsync([Required] string uniqueFileName)
Исправил

2024-07-08 11:44 UTC, DaniilRuchkin commented on Controllers/FileContoller.cs
> +[Route("api/files")]
Исправил

2024-07-08 11:47 UTC, DaniilRuchkin commented on DTO/CreateFileDto.cs
> +    public string Password { get; set; } = string.Empty;
чтобы убрать предупреждения, думал еще вместо пустой строки ? поставить
Как лучше подойти к этому решению?

2024-07-08 11:55 UTC, DaniilRuchkin commented on DTO/FileDeleteDto.cs
> +    public string Password {  get; set; } = string.Empty;
Пробел убрал

2024-07-08 12:15 UTC, DaniilRuchkin commented on DbContextFile/ManagementDbContext.cs
> +public class ManagementDbContext(DbContextOptions<ManagementDbContext> options) : DbContext(options)
Переименовал

2024-07-08 12:16 UTC, DaniilRuchkin commented on Filters/NullCheckExceptionFilter.cs
> +        {
Полностью удалить?

2024-07-08 12:18 UTC, DaniilRuchkin commented on Repositories/IRepository.cs
> +        public Task SaveFileAsync(EntityFile entity);
исправил

2024-07-08 12:27 UTC, DaniilRuchkin commented on Models/EntityFile.cs
> +public class EntityFile
исправил

2024-07-08 12:33 UTC, DaniilRuchkin commented on Models/EntityFile.cs
> +    public DateTime Time { get; set; }
Исправил

2024-07-08 12:35 UTC, DaniilRuchkin commented on Repositories/IRepository.cs
> +public interface IRepository
Исправил

2024-07-08 12:35 UTC, DaniilRuchkin commented on Repositories/Repository.cs
> +public class Repository(ManagementDbContext appDbContext) : IRepository
Исправил

2024-07-08 13:38 UTC, DaniilRuchkin commented on Repositories/IRepository.cs
> +        public Task DeleteFileTimeAsync(DateTime deleteTime);
Переименовал

2024-07-08 13:38 UTC, DaniilRuchkin commented on Repositories/IRepository.cs
> +        public Task DeleteFileAsync(EntityFile entityFile);
Исправил

2024-07-08 13:38 UTC, DaniilRuchkin commented on Repositories/Repository.cs
> +            File.Delete(file.FilePath);
Перенес логику в сервис

2024-07-08 13:39 UTC, DaniilRuchkin commented on Services/FilesServices.cs
> +public class FilesServices(IWebHostEnvironment webHostEnvironment, IRepository repository) : IFilesServices
Исправил

2024-07-08 13:41 UTC, DaniilRuchkin commented on Services/FilesServices.cs
> +            File.Delete(fileToDelete.FilePath);
Поменял местами

2024-07-08 14:09 UTC, DaniilRuchkin commented on Services/FilesCleanServices.cs
> +        int cleanIntervalDays = configuration.GetValue<int>("CleanupSettings:CleanupIntervalDays");
Переделал на IOptions

2024-07-08 14:16 UTC, DaniilRuchkin commented on Services/FilesServices.cs
> +        var passwordHasher = new PasswordHasher<string>();
Переделал под DI

2024-07-08 14:23 UTC, DaniilRuchkin commented on Services/FilesServices.cs
> +        await using (var stream = new FileStream(filePath, FileMode.Create))
Добавил флаги для асинхронности

2024-07-08 14:47 UTC, DaniilRuchkin commented on Controllers/FileContoller.cs
> +        return Ok(filePath);
А смысл плодить столько классов в таком маленьком проекте?

2024-07-09 08:42 UTC, DaniilRuchkin commented on Controllers/FileContoller.cs
> +        var filePath = Path.Combine(webRoot, dowloadedFile.UniqueName);
Перенес в сервис

2024-07-09 11:59 UTC, DaniilRuchkin commented on Repositories/Repository.cs
> +        await appDbContext.SaveChangesAsync();
1.Прокинул везде токен
2.Мне не совсем понятно, что требуется дополнительно. По текущему подходу удаляется только один файл с заданными параметрами. Если нужно удалить все файлы с такими же параметрами, то мне нужно уточнение. Если нет, то я не понимаю, что еще требуется
3.Метод работает правильно,проверил

2024-07-09 12:00 UTC, DaniilRuchkin commented on Services/IFilesServices.cs
> +    public Task<bool> DeleteFileAsync(FileDeleteDto fileDeleteDto);
Переделал

2024-07-09 12:00 UTC, DaniilRuchkin commented on Services/IFilesServices.cs
> +public interface IFilesServices
Исправил

2024-07-09 12:00 UTC, DaniilRuchkin commented on Controllers/FileContoller.cs
> +        var filePath = await services.FileSaveAsync(createFileDto);
Исправил

2024-07-15 12:28 UTC, a-kalashnikov commented on DTO/CreateFileDto.cs
> +    public string Password { get; set; } = string.Empty;
если может быть null - string?, пустую строку по умолчанию не нужно ставить

2024-07-15 12:28 UTC, a-kalashnikov commented on Filters/NullCheckExceptionFilter.cs
> +        {
да, он ничего полезного не делает

2024-07-15 12:38 UTC, a-kalashnikov approved these changes

2024-07-15 12:38 UTC, a-kalashnikov commented on .env
> +DATABASE_USER=postgres
все еще не сделал

2024-07-15 12:38 UTC, a-kalashnikov commented on Configurations/CleanSettings.cs
> +    public int DeleteBeforeDays { get; set; }
везде проставь пробелы между свойствами

2024-07-15 12:38 UTC, a-kalashnikov commented on Controllers/FileContoller.cs
> +[TypeFilter(typeof(NullCheckExceptionFilter))]
удали фильтр, он не нужен

2024-07-15 12:38 UTC, a-kalashnikov commented on Services/FileCleanService.cs
> +            await repository.SaveShangesAsync(cancellationToken);
SaveChangesAsync*
Тут он не нужен, в DeleteFile вызывается уже

2024-07-15 12:38 UTC, a-kalashnikov commented on Repositories/FileRepository.cs
> +        await appDbContext.SaveChangesAsync(cancellationToken);
почему DeleteFile, но RemoveRange?

2024-07-15 12:38 UTC, a-kalashnikov commented on Services/FileCleanService.cs
> +                await repository.DeleteFileAsync(file, cancellationToken);
о чем я ранее писал - тут проблема в том, что ты выгружаешь абсолютно все устаревшие файлы из бд, а их может быть очень много

2024-07-15 12:38 UTC, a-kalashnikov commented on Services/FileService.cs
> +            return new FileDataDto { IsSuccess = true };
нужно обрабатывать крайний случай в if, а не общий

2024-07-17 09:03 UTC, merged